### ISSUE TITLE
Dev meeting notes about transition from classic to new UI

### ISSUE THREAD

**Issue by parente** [jupyter/roadmap#20]
At the dev meeting, we had a discussion about the transition from the existing notebook UI / extension API to the new Jupyter Lab UI / API  that yielded a nice sequence of phases with criteria for transitioning among them on the board. It's mostly captured in the hackpad under Tuesday, though the criteria for transitioning went missing. (I took a stab below at adding them back in from memory.)

I don't think these phases wound up in the roadmap. I _really_ think they should to help the community understand how Jupyter Lab will come into play. 

@fperez @JamiesHQ I didn't submit a PR because I think you're actively editing the roadmap. If you'd like me to, just let me know.

@ellisonbg @sccolbert If I misremembered the criteria, please correct!

---

From https://jupyter.hackpad.com/Spring-2016-Dev-Meeting-h0y1TIAWxz1
- Phase 1:
  - A series of major releases starting with 5.0 that will have the existing notebook pages as the main UI with a JupyterLab button that takes people to the new JupyterLab page
  - These releases may have new features in the existing notebook pages, some API changes, focus on transitioning to JupyerLab.
  - These releases will have bug fixes and new features in JupyterLab designed to get JupyterLab to  Phase 2.
  - During this phase, we will continue to work on porting nbextensions to JupyterLab and building the bridge layers.
  - Explicit that people can request help for porting extensions.
  - _Criteria for transition to phase 2:_ 
    1. Jupyter Lab has all the primary functionality of the classic notebook interface.
    2. Jupyter Lab offers some interesting features beyond the classic interface.
    3. At least some important, popular extensions are ported / bridged to Jupyter Lab.
    4. Documentation and examples exist for creating Jupyter Lab plug-ins.
- Phase 2:
  - A series of major releases that will have JupyterLab as the main UI and the old notebook is available as a button
  - At this point, we start to discourage the development of new features in the existing notebook.
  - _Criteria for transition to phase 3:_ 
    1. No major development or use of the classic UI.
- Phase 3:
  - Starting with the z.0 major release. will remove the existing notebook pages.
  - Maybe offer the existing notebook as a server extension.

**Comment by fperez** [comment]
Very good point! Jamie, do you want to take a stab at this one? We can work
on the review cycle together

**Comment by JamiesHQ** [comment]
@fperez yes- I'll make the changes then submit a PR. @ellisonbg & @sccolbert can provide any additional comments on that PR

**Comment by fperez** [comment]
Great, thanks!

**Comment by parente** [comment]
Thanks for adding!
